apiVersion: v1
kind: Pod
metadata:
  name: labels
  namespace: roboshop
  labels:
    project: roboshop
    component: frontend
    environment: dev
  annotations:
     image: "https://hub.docker.com/"
     jenkinsURL: "https://jenkins.joindevops.com/build/job/roboshop/34"
spec:
  containers:
  - name: nginx
    image: nginx