apiVersion: v1
kind: Pod
metadata:
   name: env-demo
spec:
  containers:
  - name: nginx
    value: nginx
    environment:
    - name: project
      value: roboshop
    - name: course
      durations: "120hours"