kind: Service
metadata:
  name: nginx-nodeport
spec:
  selector:
    type: LoadBalancer
    project: roboshop
    component: frontend   # also check this key
    environment: dev
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    Nodeport: 32142